---
-
  become: true
  hosts: all
  become_method: sudo
  become_user: root
  tasks:
# ----- /etc/hosts ---------------------
  - name: Add host /etc/hosts
    copy:
      dest: "/etc/hosts"
      content: |
        127.0.0.1 localhost
        192.168.1.110 kube-master01
        192.168.1.120 kube-node01
        192.168.1.130 kube-node02
# --------------------------------------
# --------------------------------------
  - name: Disabled AutoUpdate
    copy:
      dest: "/etc/apt/apt.conf.d/20auto-upgrades"
      content: |
        APT::Periodic::Update-Package-Lists "0";
        APT::Periodic::Unattended-Upgrade "0";

#-Disable swap-

  - name: Swap-Off
    shell: swapoff -a

  - name: Changes /etc/fstab
    ansible.builtin.lineinfile:
      path: /etc/fstab
      state: absent
      regexp: 'swap'

  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:

  - name: Update APT
    apt:
      update_cache: yes

  - name: Install packages
    apt:
      name:
        - apt-transport-https
        - curl
        - wget
        - git
    register: install_common_packages_res
    retries: 5
    until: install_common_packages_res is success

#-Install Docker-

  - name: install dependencies for Docker
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    register: install_docker_dependencies_res
    retries: 5
    until: install_docker_dependencies_res is success

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    register: install_docker_res
    retries: 5
    until: install_docker_res is success


# Setup containerd configuration

  - name: setup containerd config - part 1
    shell: containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1

  - name: setup containerd config - part 2
    shell: sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml

  - name: Restart containerd
    service:
      name: containerd
      state: restarted
      enabled: yes

  - name: check containerd is active
    service:
      name: containerd
      state: started
      enabled: yes

# Enable, restart and check Docker

  - name: Restart Docker
    service:
      name: docker
      state: restarted
      enabled: yes

  - name: check docker is active
    service:
      name: docker
      state: started
      enabled: yes

  - name: Ensure group "docker" exists
    ansible.builtin.group:
      name: docker
      state: present

#Install Kubernetes

  - name: Changes /etc/modules-load.d/modules.conf
    ansible.builtin.lineinfile:
      path: /etc/modules-load.d/modules.conf
      line: br_netfilter \noverlay
      create: yes

  - name: Creating /etc/sysctl.d/kube.conf
    ansible.builtin.lineinfile:
      path: /etc/sysctl.d/kube.conf
      line: net.bridge.bridge-nf-call-iptables = 1
      create: yes

  - name: Add apt-key
    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

  - name: Creating /etc/apt/sources.list.d/kubernetes.list
    ansible.builtin.lineinfile:
      path: /etc/apt/sources.list.d/kubernetes.list
      line: deb https://apt.kubernetes.io/ kubernetes-xenial main
      create: yes

  - name: Update APT
    apt:
      update_cache: yes

  - name: Install kubelet kubeadm kubectl
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
    register: install_kubernetes_dependencies_res
    retries: 5
    until: install_kubernetes_dependencies_res is success

  - name: Disabled update kubelet kubeadm kubectl
    shell: apt-mark hold kubelet kubeadm kubectl

  - name: Pause for 1 minutes to build app cache
    pause:
      minutes: 1


-
  become: true
  hosts: primary-master
  become_method: sudo
  become_user: root
  tasks:
  - name: Init pod-network
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16

  - name: Pause for 1 minutes to build app cache
    pause:
      minutes: 1

  - name: Export KUBECONFIG
    shell: export KUBECONFIG=/etc/kubernetes/admin.conf

  - name: Export KUBECONFIG config
    ansible.builtin.lineinfile:
      path: /etc/environment
      line: export KUBECONFIG=/etc/kubernetes/admin.conf
      create: yes

# -------------- Ubuntu 20.04 LTS ----------------------

  - name: Apply flannel
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
###    shell: kubectl apply -f https://github.com/simff/test/blob/master/k8s/kube-flannel.yml

# ------------------------------------------------------

# -------------- Ubuntu 22.04 LTS ----------------------

#  - name: Apply flannel
#    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

#  - name: Apply flannel2
#    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml

# ------------------------------------------------------

  - name: Pause for 1 minutes to build app cache
    pause:
      minutes: 1

-
  become: true
  hosts: primary-master
  become_method: sudo
  become_user: root
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

-
  become: true
  hosts: kube-nodes
  become_method: sudo
  become_user: root
  tasks:
  - name: join cluster
    shell: "{{ hostvars['kube-master01'].join_command }}"  # set primary master
