---
-
  become: true
  hosts: all
  become_method: sudo
  become_user: root
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  
  - name: apt install openvpn
    apt:
      name: openvpn
      state: present
  
  - name: send vpn-client config
    ansible.builtin.copy: 
      src: ./.vpn-secrets/client.ovpn
      dest: /etc/openvpn/client/client.conf
      owner: root
      group: root
      mode: "0644"

  - name: enable openvpn-client service
    systemd:
      daemon_reload: yes
      name: openvpn-client@client
      state: started
      enabled: yes
